spring:
  application:
    name: "infoEvenement"
  datasource:
    url: "jdbc:mysql://localhost:8889/infoevenement"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true